- name: "Install gitea"
  hosts: all
  roles:
    - gitea
  tasks:
    - name: create gitea user
      command: >
        /usr/local/bin/gitea admin user create --admin --username {{ giteaadmin_user }}
        --password {{ giteaadmin_password }}
        --email {{ giteaadmin_email }}
        -c /etc/gitea/gitea.ini
      become: yes
      become_user: gitea

    - name: add gitea subpath to nginx.conf
      ansible.builtin.blockinfile:
        path: /etc/nginx/nginx.conf
        insertafter: "^.*server_name student.*"
        block: |
            # Note: Trailing slash
            location /gitea/ {
            proxy_pass http://localhost:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            }

    - name: Restart nginx
      ansible.builtin.systemd:
        state: restarted
        #daemon_reload: yes
        name: nginx



